## Problem 4

This part of the exam will test your skills maneuvering in Pandas, as well as your ability to think of ways to improve computing and memory efficiency.

The dataset used in these exercises, ["Offensive Baseball Stats Through 2016"](https://www.kaggle.com/baseballstatsonline/offensive-baseball-stats-through-2016), Version 1, is from Kaggle user baseballstatsonline.com. The dataset is a fairly rich set of players and statistics, but for the purposes of these exercises you do not need to know anything in particular about the columns' meaning unless it is otherwise explained below. The dataset has been modified slightly for the purpose of some exercises. 

Run the following code cell to download the data and create some necessary functions. Good luck!

**Note:** If you are running this notebook locally please make sure you run the same version of pandas as in Vocareum enviroment.

In [1]:
import pandas as pd
import numpy as np
from cse6040utils import canonicalize_tibble, tibbles_are_equivalent    

DATA_PATH = "../resource/asnlib/publicdata/"  # This path is hard-coded to work on Vocareum only
baseball = pd.read_csv('{}mlb_off_stats_modified.csv'.format(DATA_PATH),header=0)
baseball_test = baseball.iloc[np.arange(1, baseball.shape[0], 200)]
baseball.head(5)

,Player Name,playerID,yearID,stint,teamID,name,park,lgID,G,AB,...,birthCountry,birthState,birthDay,birthMonth,birthYear,Weight,Height,bats,200HitSeason,Decade
0,Carroll,carroch01,1884-01-01,1,WSU,Washington Nationals,NaN,UA,4,16,...,NaN,NaN,0,0,0,0,0.000000,NaN,0,1800
1,Gavern,gaver01,1874-01-01,1,BR2,Brooklyn Atlantics,Union Grounds,NaN,1,0,...,NaN,NaN,0,0,0,0,0.000000,NaN,0,1800
2,McRemer,mcrem01,1884-01-01,1,WSU,Washington Nationals,NaN,UA,1,0,...,NaN,NaN,0,0,0,0,0.000000,NaN,0,1800
3,Sterling,sterljo01,1890-01-01,1,PH4,Philadelphia Athletics,Jefferson Street Grounds,AA,1,0,...,NaN,NaN,0,0,0,0,0.000000,NaN,0,1800
4,A. J. Ellis,ellisaj01,1/1/14,1,LAN,Los Angeles Dodgers,Dodger Stadium,NL,0,0,...,USA,MO,9,4,1981,0,6.166666,R,0,2020

First things first, let's delete unnecessary columns.

**Exercise 0** (1 point): Complete the `remove_redundant_columns` function that takes dataframe `df` and returns a _**new**_ dataframe  _excluding_ the following columns:
- Any column with the word 'Career' in it's name
- Any column with the string 'birth' in it's name
- 200HitSeason, Decade, Player Name, name, park, lgID, bats

In [15]:
def remove_redundant_columns(df):
    df1 = df.copy()

    
    df1 = df1[df1.columns.drop(list(df1.filter(regex=r'Career')))]
    df1 = df1[df1.columns.drop(list(df1.filter(regex=r'birth')))]

    df1 = df1.drop(['200HitSeason', 'Decade', 'Player Name', 'name', 'park', 'lgID', 'bats'], axis=1)
    
    
    return df1

To test your solution we have created a data frame `baseball_test` which is a much smaller sample of the orginial dataframe `baseball`. We also provided how the output for `remove_redundant_columns(baseball_test)` should look like in data-frame `df_ex0_soln_instructor`. 

**Note**: The below test case is designed just for the purpose of debugging and will not be used for grading.

In [16]:
# (0 Points) `remove_redundant_columns_dummy`: Test cell 1
from pandas.util.testing import assert_frame_equal

df_ex0_soln_instructor = canonicalize_tibble(pd.read_csv('ex0_soln.csv'))
df_ex0_soln_yours = canonicalize_tibble(remove_redundant_columns(baseball_test))

assert type(df_ex0_soln_yours) == type(df_ex0_soln_instructor), 'Your output does not return a pandas dataframe'
assert_frame_equal(df_ex0_soln_instructor, df_ex0_soln_yours)

print('Passed!')

del df_ex0_soln_instructor
del df_ex0_soln_yours

Passed!

Testing your solution on the original dataframe

In [17]:
# (1 Point) `remove_redundant_columns`: Test cell 2
assert tibbles_are_equivalent(remove_redundant_columns(baseball), -8278288771535832348), "Tibbles don't match!" 
print("Passed!")

Passed!

Great! If the above test case passed then let's remove columns from the original dataset `df` using `remove_redundant_columns(baseball)`

In [18]:
baseball_test = remove_redundant_columns(baseball_test)
baseball = remove_redundant_columns(baseball)
baseball.shape

(101766, 37)

#### Shrinking the dataset.

**Exercise 1** (1 point). Write a function `shrink_data()` which takes the dataframe `df` and returns a **new** dataframe where:

* the column `yearID` should be converted to `pandas datetime` format; **and**
* only rows such that `yearID` is from 2000 (inclusive) to 2016 (inclusive) are returned.

> Hint: Regarding the first condition, see [`pandas.to_datetime()`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html).

In [25]:
import datetime

def shrink_data(df):
    df1 = df.copy()
    df1['yearID'] = pd.to_datetime(df.yearID)
    df1 = df1[(df1.yearID >= datetime.date(2000,1,1)) & (df1.yearID <= datetime.date(2016, 12, 31))]
    return df1

The test below will test your solution on a the smaller sample `baseball_test`. 

**Note**: The below test case is designed just for the purpose of debugging and will not be used for grading.

In [26]:
# (0 Points) `shrink_data_dummy`:  Test cell 1

from pandas.util.testing import assert_frame_equal

df_ex1_soln_instructor = canonicalize_tibble(pd.read_csv('ex1_soln.csv', parse_dates=['yearID']))
df_ex1_soln_yours = canonicalize_tibble(shrink_data(baseball_test))

assert type(df_ex1_soln_yours) == type(df_ex1_soln_instructor), 'Your output does not return a pandas dataframe'
assert_frame_equal(df_ex1_soln_instructor, df_ex1_soln_yours)

print('Passed!')
del df_ex1_soln_instructor
del df_ex1_soln_yours

Passed!

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: FutureWarning: Comparing Series of datetimes with 'datetime.date'.  Currently, the
'datetime.date' is coerced to a datetime. In the future pandas will
not coerce, and a TypeError will be raised. To retain the current
behavior, convert the 'datetime.date' to a datetime with
'pd.Timestamp'.

Testing solution on original dataframe

In [27]:
# (1 Points) `shrink_data`: Test cell
assert tibbles_are_equivalent(shrink_data(baseball), 1828659959833542576), "Tibbles don't match!" 
print("Passed!")

Passed!

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: FutureWarning: Comparing Series of datetimes with 'datetime.date'.  Currently, the
'datetime.date' is coerced to a datetime. In the future pandas will
not coerce, and a TypeError will be raised. To retain the current
behavior, convert the 'datetime.date' to a datetime with
'pd.Timestamp'.

Let's shrink the orginial dataframe now.

In [28]:
baseball_test = shrink_data(baseball_test)
baseball = shrink_data(baseball)
baseball.shape

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: FutureWarning: Comparing Series of datetimes with 'datetime.date'.  Currently, the
'datetime.date' is coerced to a datetime. In the future pandas will
not coerce, and a TypeError will be raised. To retain the current
behavior, convert the 'datetime.date' to a datetime with
'pd.Timestamp'.

(31805, 37)

Several players appear in the dataset more than once. This is because they played for one team, then were traded or moved to another. Currently, the combination of `playerID`, `stint`, and `teamID` is unique within each row. We want to transform this into a dataset that contains the all _minimum_ characteristics of each player over all the teams and stints the player had.

**Exercise 2** (3 points). Complete the function `transform_baseball_data(df)` and return a **new** dataframe such that, for each unique player (`playerID`):
- only the earliest `yearID` is retained;
- only the _lowest_ value of every numerical column is retained;
- the columns `stint` and `teamID` are not retained;
- after tranformation the numerical values are rounded to nearest 10 and converted to integer. For example, the value 15.33 rounded to nearest 10 is 20, and the value 14.999 is rounded to 10. For cases like 5, 15, 25, etc., such a value `v` would be the same as that produced by `round(v, -1)` in standard Python.

The final data frame will have one row per unique player with the columns retained and transformed as outlined above.

A natural way to start is to group the data frame `df` by `playerID`. However, for your final result, be sure that `playerID` is **not** the index. (That is, be sure your final result is a tibble.)

> Hint: A relatively clean solution may be had by exploiting features of the [`.agg()` method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.core.groupby.DataFrameGroupBy.agg.html) available for `.groupby()` objects produced when called on `DataFrame` objects.

In [86]:

def transform_baseball_data(df):
    
    df1 = df.copy()
    df1 = df1.drop(['stint', 'teamID'], axis=1)
    
    df1 = df1.groupby('playerID').min().reset_index()
    df1 = df1.round(-1)
    df2 = df1.iloc[:, 2:].astype(int, errors='ignore').reset_index() 
    df1 = df1[['playerID', 'yearID']].reset_index()
    
    df3 = df1.merge(df2, how='left', on='index')
    df3 = df3.drop('index', axis=1)
    
    return df3
    
transform_baseball_data(baseball_test)
#df_ex2_soln_instructor.head()

,playerID,yearID,G,AB,R,H,2B,3B,HR,RBI,...,OPS,ISO,BB%,K%,BB/K,BAPIP,SB%,Weighted162Factor,Weight,Height
0,adamsba01,2010-01-01,0,0,10,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
1,adamsda02,2013-01-01,0,0,0,0,0,0,0,10,...,0,0,0,0,0,0,0,0,0,10
2,altheaa01,2016-01-01,0,200,20,0,10,0,0,20,...,0,0,0,0,0,0,0,0,220,10
3,alvarhe01,2015-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,200,10
4,anderfr01,2015-01-01,0,80,0,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
5,anderjo01,2006-01-01,0,0,60,0,20,0,0,0,...,0,0,0,0,0,0,0,10,180,10
6,andruel01,2011-01-01,150,590,100,0,0,0,0,60,...,0,0,0,0,0,0,0,10,0,10
7,armstsh01,2016-01-01,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
8,atchisc01,2010-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
9,barfijo02,2009-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,190,10
10,bartoda02,2007-01-01,20,0,0,20,10,0,0,10,...,0,0,0,0,0,0,0,0,0,10
11,belljo01,2012-01-01,0,50,0,10,0,0,0,0,...,0,0,0,0,0,0,0,0,230,10
12,beltrad01,2012-01-01,0,0,0,0,0,0,0,100,...,0,0,0,0,0,0,0,0,220,10
13,beltrca01,2015-01-01,130,480,0,130,0,0,20,70,...,0,0,0,0,0,0,0,20,220,10
14,benesal01,2000-01-01,30,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,220,10
15,bentoru01,2014-01-01,40,0,0,0,0,0,0,10,...,0,0,0,0,0,0,0,0,0,10
16,bluejji01,2016-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,200,10
17,bourju01,2016-01-01,0,280,0,70,0,0,0,0,...,0,0,0,0,0,0,0,0,260,10
18,boydma01,2016-01-01,20,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,220,10
19,bradlbi01,2008-01-01,0,550,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
20,bumgama01,2014-01-01,0,70,10,0,0,0,0,0,...,0,0,0,0,0,0,0,0,250,10
21,burnsbi01,2008-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
22,burrebr01,2011-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,180,10
23,bushdo01,2016-01-01,0,550,70,120,0,10,0,0,...,0,0,0,0,0,0,0,0,140,10
24,callami01,2004-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,190,10
25,casanra01,2008-01-01,0,60,0,0,0,0,0,10,...,0,0,0,0,0,0,0,0,200,10
26,castrju01,2001-01-01,100,0,30,0,10,0,0,0,...,0,0,0,0,0,0,0,0,190,10
27,castrmi01,2015-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,190,10
28,chacijh01,2010-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
29,chancfr01,2007-01-01,110,380,60,0,0,0,0,50,...,0,0,0,0,0,0,0,10,190,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,sanchan02,2013-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
129,sanchdu01,2006-01-01,50,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
130,segurje01,2012-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,200,10
131,shoppke01,2012-01-01,0,140,20,40,10,0,0,0,...,0,0,0,0,0,0,0,0,220,10
132,smithha03,2002-01-01,0,180,10,40,0,0,0,0,...,0,0,0,0,0,0,0,0,160,10
133,speaktr01,2007-01-01,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
134,spoonti01,2003-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
135,stangda01,2010-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,240,10
136,stephga01,2002-01-01,0,10,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
137,stewash01,2005-01-01,0,0,70,150,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
138,sweenbi02,2007-01-01,0,190,0,50,0,0,0,0,...,0,0,0,0,0,0,0,10,0,10
139,tarasto01,2002-01-01,0,100,0,20,0,0,10,20,...,0,0,0,0,0,0,0,0,0,10
140,tatumcr01,2009-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
141,tekotbl01,2011-01-01,0,30,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
142,valenjo04,2004-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
143,wakefho01,2006-01-01,80,0,20,0,10,0,0,0,...,0,0,0,0,0,0,0,0,0,10
144,weathda01,2003-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,10,0,10
145,weaveje01,2001-01-01,30,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,200,10
146,weaveje02,2011-01-01,30,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
147,wellsja02,2008-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,200,10
148,wengedo01,2001-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
149,westse01,2010-01-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,280,10
150,wilsoja02,2005-01-01,160,0,60,0,0,10,10,50,...,0,0,0,0,0,0,0,0,200,10
151,winnra01,2006-01-01,0,0,0,150,0,0,10,60,...,0,0,0,0,0,0,0,0,0,10
152,wolfepo01,2014-01-01,10,0,0,10,0,0,0,0,...,0,0,0,0,0,0,0,0,170,10
153,younger01,2005-01-01,0,140,20,0,10,0,0,10,...,0,0,0,0,0,0,0,0,0,10
154,younger03,2013-01-01,90,370,50,90,20,0,0,0,...,0,0,0,0,0,0,0,0,0,10
155,zambrvi01,2004-01-01,0,10,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,190,10
156,zaungr01,2007-01-01,0,0,40,80,20,0,0,0,...,0,0,0,0,0,0,0,0,0,10
157,zinngu01,2013-01-01,0,0,0,0,0,0,0,20,...,0,0,0,0,0,0,0,0,0,10

To test your solution we have provided solution for the dataframe `baseball_test` 

**Note**: The below test case is designed just to help you debug.

In [87]:
# (0 Points) `transform_baseball_data_dummy`: Test cell
from pandas.util.testing import assert_frame_equal

df_ex2_soln_instructor = canonicalize_tibble(pd.read_csv('ex2_soln.csv', parse_dates=['yearID']))
df_ex2_soln_yours = canonicalize_tibble(transform_baseball_data(baseball_test))

assert type(df_ex2_soln_yours) == type(df_ex2_soln_instructor), 'Your output does not return a pandas dataframe'
assert_frame_equal(df_ex2_soln_instructor, df_ex2_soln_yours)

print('Passed!')

del df_ex2_soln_yours

Passed!

Testing on original dataframe

In [88]:
# (3 Points) `transform_baseball_data`: Test cell
assert tibbles_are_equivalent(baseball, 1828659959833542576), "Tibbles don't match!" 
print("Passed!")

Passed!

Let's transform the original dataframe `baseball`

In [89]:
baseball_test = transform_baseball_data(baseball_test)
baseball = transform_baseball_data(baseball)
baseball.shape

(7403, 35)

## Faster matrix products

Now, we're going to change direction just a little. Don't worry, you don't need to know anything conceptual about what we're about to do; all you need to do is think of a faster way to apply the formula to generate its output based on the course material that's already been covered.

One way of calculating the variance matrix $\Sigma$ of a dataset is given by the formula

$$\Sigma=E(XX^T)-\mu\mu^T$$

where $X$ is an $n \times m$ matrix containing each data point and $\mu$ is an $n \times m$ matrix containing the column means of those data points.

For this exercise, we will simply be calculating the parameter given to the expectation $E(\cdot)$ function, $XX^T$. You can see in the cell below that this has already been done for you, but your task will be to figure out how to run `X.dot(X.T)` faster than we did.

First, run the code cell below to establish an estimate time for the output.

In [90]:
import numpy as np
import timeit

X = baseball[[x for x in baseball.columns if x not in ['playerID','yearID']]].values

print("Matrix X is of size {}".format(X.shape))

Matrix X is of size (7403, 33)

In [91]:
def slow_calc(X):
    return X.dot(X.T)

slow_time = timeit.timeit("slow_calc(X)",setup="from __main__ import slow_calc, X", number = 1)
print("Your estimated time for X.dot(X.T) is "+' {0:.4f}'.format(slow_time) + " seconds.")

Your estimated time for X.dot(X.T) is  3.2104 seconds.

**Exercise 3** (5 points): Come up with a way to make the matrix-times-transpose function faster than `slow_calc(X)`. Implement your method as the function `fast_calc()`. To get the full 5 points, your method must be **2.5 times faster**. You can get partial credit: 3 points if your function is at least 2 times faster and 1 point if your function is at least 1.5 times faster.

The input to `fast_calc` is of type `numpy.ndarray` and expected output is also of type `numpy.ndarray`

**Note**: The variable named `number_of_runs` determines how many times `fast_calc` will be run against the timer. You may lower `number_of_runs` for debugging purposes, but must increase it to at least 5 to pass the test cell. You may also import libraries you would like to use.

**The benchmarks for this question are set according to Vocareum environment.** You might get different results if you test on your system. So please test your results here.

> This exercise requires some creativity in thinking about how to exploit structure present in the problem.

In [127]:
import numpy as np
from scipy.sparse import coo_matrix

number_of_runs = 5

def fast_calc(X):
    X = coo_matrix(X)
    XT = coo_matrix(X.T)
    calc = X.dot(XT)
    return  calc.toarray()

Run this test to get on 1 point for a solution that is at least 1.5 times faster

In [128]:
# (1 point) `speed_test_1`: Test cell
for i in range(5):
    nrows = np.random.randint(5) + 1
    ncols = np.random.randint(5) + 1
    A = np.random.rand(nrows, ncols)
    your_out = fast_calc(A)
    instructor_out = slow_calc(A)
    assert type(your_out) == type(A), "Please return object of type {}".format(type(A))
    np.testing.assert_array_almost_equal(instructor_out, your_out, decimal = 5)

assert X.shape == (7403, 33), "You have modified X"

slow_time = timeit.timeit("slow_calc(X)",setup="from __main__ import slow_calc, X", number = number_of_runs)/number_of_runs
student_time = timeit.timeit("fast_calc(X)", setup="from __main__ import fast_calc, X",number = number_of_runs)/number_of_runs
print("Your baseline time for X.dot(X.T) is "+'{0:.4f}'.format(student_time)+" seconds, which is "+'{0:.2f}'.format(slow_time/student_time)+ " times faster than our method.")
assert student_time/slow_time <= 0.75, "Your solution isn't at least 1.5 times faster than our solution."
assert number_of_runs >= 5, "number_of_runs needs to be >=5 to pass this cell."

print("Passed!")

Your baseline time for X.dot(X.T) is 0.9710 seconds, which is 3.16 times faster than our method.
Passed!

Run this test to get 2 points for a solution that is at least 2 times faster

In [129]:
# (2 point) `speed_test_3`: Test cell
for i in range(5):
    nrows = np.random.randint(5) + 1
    ncols = np.random.randint(5) + 1
    A = np.random.rand(nrows, ncols)
    your_out = fast_calc(A)
    instructor_out = slow_calc(A)
    assert type(your_out) == type(A), "Please return object of type {}".format(type(A))
    np.testing.assert_array_almost_equal(instructor_out, your_out, decimal = 5)

assert X.shape == (7403, 33), "You have modified X"

slow_time = timeit.timeit("slow_calc(X)",setup="from __main__ import slow_calc, X", number = number_of_runs)/number_of_runs
student_time = timeit.timeit("fast_calc(X)", setup="from __main__ import fast_calc, X",number = number_of_runs)/number_of_runs
print("Your baseline time for X.dot(X.T) is "+'{0:.4f}'.format(student_time)+" seconds, which is "+'{0:.2f}'.format(slow_time/student_time)+ " times faster than our method.")
assert student_time/slow_time <= 0.40, "Your solution isn't at least 2.5 times faster than our solution."
assert number_of_runs >= 5, "number_of_runs needs to be >=5 to pass this cell."

print("Passed!")

Your baseline time for X.dot(X.T) is 0.9588 seconds, which is 3.22 times faster than our method.
Passed!

Run this test to get 2 points for a solution that is at least 2.5 times faster

In [130]:
# (2 point) `speed_test_3`: Test cell
for i in range(5):
    nrows = np.random.randint(5) + 1
    ncols = np.random.randint(5) + 1
    A = np.random.rand(nrows, ncols)
    your_out = fast_calc(A)
    instructor_out = slow_calc(A)
    assert type(your_out) == type(A), "Please return object of type {}".format(type(A))
    np.testing.assert_array_almost_equal(instructor_out, your_out, decimal = 5)

assert X.shape == (7403, 33), "You have modified X"

slow_time = timeit.timeit("slow_calc(X)",setup="from __main__ import slow_calc, X", number = number_of_runs)/number_of_runs
student_time = timeit.timeit("fast_calc(X)", setup="from __main__ import fast_calc, X",number = number_of_runs)/number_of_runs
print("Your baseline time for X.dot(X.T) is "+'{0:.4f}'.format(student_time)+" seconds, which is "+'{0:.2f}'.format(slow_time/student_time)+ " times faster than our method.")
assert student_time/slow_time <= 0.40, "Your solution isn't at least 2.5 times faster than our solution."
assert number_of_runs >= 5, "number_of_runs needs to be >=5 to pass this cell."

print("Passed!")

Your baseline time for X.dot(X.T) is 1.0022 seconds, which is 3.15 times faster than our method.
Passed!

**Fin!** Remember to test your solutions by running them as the autograder will: restart the kernel and run all cells from "top-to-bottom." Also remember to submit to the autograder; otherwise, you will **not** get credit for your hard work!